turn_taking_14_18:
  child_turn_duration_mean_sec: 3.026
  child_turn_duration_std_sec: 2.046
  adult_turn_duration_mean_sec: 3.326
  adult_turn_duration_std_sec: 2.355
  pause_mean_sec: 0.008
  pause_std_sec: 0.081
  overlap_probability: 0.118
  overlap_dur_mean_sec: 0.006
  overlap_dur_std_sec: 0.034
turn_taking_34_38:
  child_turn_duration_mean_sec: 3.271
  child_turn_duration_std_sec: 2.11
  adult_turn_duration_mean_sec: 2.86
  adult_turn_duration_std_sec: 1.985
  pause_mean_sec: 0.0
  pause_std_sec: 0.004
  overlap_probability: 0.121
  overlap_dur_mean_sec: 0.007
  overlap_dur_std_sec: 0.043
